name: PR
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shfmt
        shell: bash
        run: sudo snap install shfmt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run formatters
        shell: bash
        run: |
          invoke check-format

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        shell: bash
        run: invoke lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Run unit tests
        shell: bash
        run: |
          mkdir -p .testresults
          bats -r tests/unit -F junit -o .testresults
          ls
          ls -la .testresults

      - name: Setup testspace publisher
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
        if: always()
      - name: Publish test results
        run: testspace .testresults
        if: always()
