name: PR
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shfmt
        shell: bash
        run: sudo snap install shfmt

      - name: Run shfmt
        shell: bash
        run: shfmt -d .

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # ShellCheck is installed by default
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-apt-packages
      # - name: Install ShellCheck
      #   shell: bash
      #   run: sudo apt install shellcheck

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
